services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"  
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__STORAGE__PATH=/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant-data:
    driver: local

networks:
  default:
    external: true
    name: local_network