version: '3.5'
services:
  bitbucket:
    image: atlassian/bitbucket-server
    container_name: bitbucket
    ports:
    - 7990:7990
    - 7999:7999
    volumes:
    - bitbucket-vol:/var/atlassian/application-data/bitbucket
    networks:
    - network

volumes:
  bitbucket-vol:
    driver: local

networks:
  network:
    driver: bridge
