services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    image: n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      # Deployment settings
      - N8N_HOST=${DOMAIN}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=development
      - WEBHOOK_URL=https://${DOMAIN}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      # Langfuse Tracing
      - LANGFUSE_BASEURL=${LANGFUSE_BASEURL}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      # Allow external packages
      - NODE_FUNCTION_ALLOW_EXTERNAL=langfuse-langchain
      # GOOGLE MODEL
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # isolate n8n
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_TEMPLATES_ENABLED=false
      - EXTERNAL_FRONTEND_HOOKS_URLS=
      - N8N_DIAGNOSTICS_CONFIG_FRONTEND=
      - N8N_DIAGNOSTICS_CONFIG_BACKEND=
    volumes:
      - n8n_data:/home/node/.n8n
    extra_hosts:
      - ${LANGFUSE_ENDPOINT}
volumes:
  n8n_data:
    driver: local

networks:
  default:
    external: true
    name: local_network