version: '3.5'
services:
  registry:
    image: registry
    container_name: registry
    restart: unless-stopped
    volumes:
    - ${PWD}/data/certs:/certs
    - ${PWD}/data/auth:/auth
    - ${PWD}/data/registry:/var/lib/registry
    environment:
    - REGISTRY_AUTH=htpasswd
    - REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
    - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.cert
    - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
    ports:
    - 5000:5000
    networks:
    - registry

networks:
  registry:
    driver: bridge
