services:
  mcp-gateway:
    image: mcp-gateway:latest
    ports:
      - "5080:5080"
    env_file: .env
    environment:
      - NODE_ENV=production
    volumes:
      # Mount SQLite database to persist data
      - sqlite_data:/app/data
    restart: unless-stopped
    depends_on:
      - docker-proxy
    # Resource limits for production
    deploy:
      resources:  
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    # Log configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5555/api/health"]
      interval: 30s
      timeout: 3s
      start_period: 15s
      retries: 3

  # Docker socket proxy for secure Docker access
  docker-proxy:
    container_name: docker-proxy-prod
    image: lscr.io/linuxserver/socket-proxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    tmpfs:
      - /run
    restart: unless-stopped
    read_only: true
    environment:
      - PING=1
      - POST=1
      - PLUGINS=1
      - CONTAINERS=1
      - IMAGES=1
      - INFO=1
      - VOLUMES=1
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M

volumes:
  sqlite_data:
    driver: local

networks:
  default:
    external: true
    name: local_network