services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    #privileged: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data-vol:/data
    ports:
      - 9443:9443

volumes:
  portainer-data-vol:
    driver: local

networks:
  default:
    external: true
    name: local_network
