FROM alpine:latest

RUN addgroup -S prisma-group && adduser -S prisma-user -G prisma-group  
RUN apk add --no-cache python3 py3-pip gcc musl-dev python3-dev libffi-dev curl
RUN pip3 install --upgrade pip && pip3 install setuptools wheel
RUN pip3 install bridgecrew
USER prisma-user
